version: "3"
services:
  sslupdater:
    container_name: atd-sslupdater
    image: atddocker_sslupdater:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
  uptime:
    container_name: atd-uptime
    image: atddocker_uptime:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
    networks:
      - atd_nginx
  login:
    container_name: atd-login
    image: atddocker_login:1.0
    restart: always
    hostname: devbox
    networks:
      - atd_nginx
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd/topologies:/opt/atd/topologies:ro
      - /home/arista/arista-dir:/home/arista:rw
      - /home/arista/.ssh:/home/arista/.ssh:rw
  cvpupdater:
    container_name: atd-cvpupdater
    image: atddocker_cvpupdater:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /home/arista/arista-dir/cvp:/home/arista/cvp:ro
      - /opt/atd:/opt/atd:ro
      - cvp_dir:/home/arista/CVP_DATA:rw
  gitconfigletsync:
    container_name: atd-gitconfigletsync
    image: atddocker_gitconfigletsync:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd:/opt/atd:ro
      - cvp_dir:/home/arista/CVP_DATA:rw
  kvmbuilder:
    container_name: atd-kvmbuilder
    image: atddocker_kvmbuilder:1.0
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd:/opt/atd:ro
      - /home/atdadmin/KVM_scripts:/home/atdadmin/kvm:rw
  ceosbuilder:
    container_name: atd-ceosbuilder
    image: atddocker_ceosbuilder:1.0
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd:/opt/atd:ro
      - /opt/ceos:/opt/ceos:rw
  uilanding:
    container_name: atd-uilanding
    image: atddocker_uilanding:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd:/opt/atd:ro
    networks:
      - atd_nginx
  labguides:
    container_name: atd-labguides
    image: atddocker_labguides:1.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/atd:/etc/atd:ro
      - /opt/atd:/opt/atd:ro
    networks:
      - atd_nginx
  freerad:
    container_name: atd-freeradius
    image: atddocker_freerad:1.0
    restart: always
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
  nginx:
    container_name: atd-nginx
    image: atddocker_nginx:1.0
    restart: always
    depends_on:
      - uilanding
      - guacamole
      - jenkins
    ports:
      - "80:80/tcp"
    networks:
      - atd_nginx
  desktop:
    container_name: atd-desktop
    image: atddocker_desktop:1.0
    restart: always
    hostname: devbox
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/arista/GUI_Desktop:/home/arista/Desktop/Files:rw
      - /home/arista/.ssh:/home/arista/.ssh:rw
      - /home/arista/arista-dir/hosts:/etc/hosts:ro
    networks:
      - guac_net
  guacd:
    container_name: atd-guacd
    image: atddocker_guacd:1.0
    restart: always
    networks:
      - guac_net
  guacamole:
    container_name: atd-guacamole
    image: atddocker_guacamole:1.0
    restart: always
    volumes:
      - /home/arista/infra/user-mapping.xml:/root/.guacamole/user-mapping.xml:ro
    depends_on: 
      - guacd
    networks:
      - guac_net
      - atd_nginx
    environment: 
      - GUACD_HOSTNAME=atd-guacd
  jenkins:
    container_name: atd-jenkins
    image: atddocker_jenkins:1.0
    restart: always
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - atd_nginx
    volumes:
      - jenkins_home:/var/jenkins_home
  robot:
    container_name: atd-robot
    image: mpergament/aristarobot:latest
    restart: always
    networks:
      - atd_nginx
    volumes:
      - /home/atdadmin/robot:/home/robot
      - /etc/atd/ACCESS_INFO.yaml:/etc/atd/ACCESS_INFO.yaml
      - /home/arista/arista-dir:/home/arista:rw
      - /opt/atd/topologies:/opt/atd/topologies
  ansible:
    container_name: atd-ansible-avd
    image: atddocker_ansiblegui:1.0
    restart: always
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/arista/.ssh:/home/arista/.ssh:rw
      - /home/arista/arista-dir/hosts:/etc/hosts:ro
    networks:
      - guac_net
  labdeploy:
    container_name: atd-labdeploy
    image: atddocker_labdeploy:1.0
    restart: always
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/arista/arista-dir/hosts:/etc/hosts:ro
    networks:
      - atd_nginx

networks:
  guac_net:
  atd_nginx:
volumes:
  atd_labguides:
  atd_http:
  jenkins_home:
  cvp_dir: